//! Prepare Tor hidden-service keys and config, then exit.
//!
//! Used by the Docker entrypoint before starting `tor` and `sikka-node`.

use std::fs;
use std::path::Path;

use sikka_common::error::{Error, Result};
use sikka_common::constants::DEFAULT_PORT;
use crate::NodeConfig;
use sikka_onion::OnionIdentity;
use sikka_wallet::Keystore;

/// Load the node key, write C-Tor HS material + `torrc`, print the onion URL.
pub fn prepare_tor(config: &NodeConfig) -> Result<String> {
    let keypair = if let Some(hex) = &config.private_key {
        parse_private_key(hex)?
    } else {
        Keystore::load_or_create(&config.key_path)?.keypair()?
    };
    // Persist so the subsequent sikka-node process sees the same key.
    Keystore::from_keypair(&keypair).save(&config.key_path)?;

    let onion = OnionIdentity::from_keypair(&keypair)
        .map_err(|e| Error::Other(format!("onion derivation failed: {e}")))?;
    onion
        .write_ctor_dir(config.arti_ctor_path())
        .map_err(|e| Error::Other(format!("cannot write HS keys: {e}")))?;

    let socks = config
        .tor_socks
        .clone()
        .unwrap_or_else(|| sikka_common::constants::DEFAULT_TOR_SOCKS.to_string());
    let (socks_host, socks_port) = split_host_port(&socks)?;

    write_torrc(
        &config.data_dir.join("torrc"),
        &config.arti_ctor_path(),
        &config.data_dir.join("tor-data"),
        socks_host,
        socks_port,
        DEFAULT_PORT,
    )?;

    // Arti-shaped paths kept for a future Arti sidecar swap.
    fs::create_dir_all(config.arti_state_path())
        .map_err(|e| Error::Other(format!("cannot create arti state: {e}")))?;
    fs::create_dir_all(config.arti_cache_path())
        .map_err(|e| Error::Other(format!("cannot create arti cache: {e}")))?;
    write_arti_toml(config, &socks, DEFAULT_PORT)?;

    Ok(onion.advertise_url())
}

fn write_torrc(
    path: &Path,
    hs_dir: &Path,
    data_dir: &Path,
    socks_host: &str,
    socks_port: u16,
    target_port: u16,
) -> Result<()> {
    fs::create_dir_all(data_dir).map_err(|e| Error::Other(format!("tor data dir: {e}")))?;
    if let Some(parent) = path.parent() {
        fs::create_dir_all(parent).map_err(|e| Error::Other(format!("torrc parent: {e}")))?;
    }
    // Virtport 80 matches `OnionIdentity::advertise_url()` (`http://….onion`
    // with no explicit port). Peers and the self-check dial the default HTTP port.
    let contents = format!(
        "\
DataDirectory {data}
SocksPort {socks_host}:{socks_port}
SocksPolicy accept 127.0.0.1/32
SocksPolicy reject *
HiddenServiceDir {hs}
HiddenServicePort 80 127.0.0.1:{target_port}
Log notice stderr
",
        data = data_dir.display(),
        hs = hs_dir.display(),
    );
    fs::write(path, contents).map_err(|e| Error::Other(format!("cannot write torrc: {e}")))?;
    Ok(())
}

fn write_arti_toml(config: &NodeConfig, socks: &str, target_port: u16) -> Result<()> {
    let (_host, port) = split_host_port(socks)?;
    let contents = format!(
        r#"# Generated by sikka-node --prepare-tor (for a future Arti sidecar).
# The Docker image currently runs the Tor daemon with matching C-Tor keys.

[application]
allow_running_as_root = false

[proxy]
socks_listen = {port}

[storage]
cache_dir = "{cache}"
state_dir = "{state}"

[storage.keystore]
enabled = true

[[storage.keystore.ctor.services]]
id = "sikka-ctor"
path = "{ctor}"
nickname = "sikka"

[onion_services.sikka]
proxy_ports = [
    ["80", "127.0.0.1:{target_port}"],
]
"#,
        cache = config.arti_cache_path().display(),
        state = config.arti_state_path().display(),
        ctor = config.arti_ctor_path().display(),
        port = port,
        target_port = target_port,
    );
    fs::write(config.arti_config_path(), contents)
        .map_err(|e| Error::Other(format!("cannot write arti.toml: {e}")))?;
    Ok(())
}

fn split_host_port(socks: &str) -> Result<(&str, u16)> {
    let socks = socks.strip_prefix("socks5h://").unwrap_or(socks);
    let socks = socks.strip_prefix("socks5://").unwrap_or(socks);
    let (host, port) = socks.rsplit_once(':').ok_or_else(|| {
        Error::Other(format!("Tor SOCKS '{socks}' must be host:port"))
    })?;
    let port: u16 = port
        .parse()
        .map_err(|_| Error::Other(format!("invalid SOCKS port in '{socks}'")))?;
    Ok((host, port))
}

fn parse_private_key(hex: &str) -> Result<sikka_crypto::Keypair> {
    let clean = hex.trim().strip_prefix("0x").unwrap_or(hex.trim());
    let bytes = ::hex::decode(clean).map_err(|_| Error::InvalidHex)?;
    match bytes.len() {
        32 => {
            let seed: [u8; 32] = bytes.try_into().expect("length checked");
            Ok(sikka_crypto::Keypair::from_seed(&seed)?)
        }
        sikka_crypto::SK_LEN => Ok(sikka_crypto::Keypair::from_private_bytes(&bytes)?),
        n => Err(Error::Other(format!(
            "SIKKA_PRIVATE_KEY must be a 32-byte seed or {}-byte secret, got {n} bytes",
            sikka_crypto::SK_LEN
        ))),
    }
}
